_wandb:
    value:
        cli_version: 0.25.0
        e:
            nyukj6wb6520ksdrr8zua6otp025cjq8:
                args:
                    - --mode
                    - sweep
                    - --count
                    - "20"
                codePath: rabi_pinn_pura_wandb.py
                codePathLocal: rabi_pinn_pura_wandb.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "511190233088"
                        used: "459512176640"
                email: alberto.estrada@udea.edu.co
                executable: C:\Users\CAMILO\Documents\PINNs\pinn_env\Scripts\python.exe
                host: LAPTOP-9ACAG0LI
                memory:
                    total: "16456183808"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\CAMILO\Documents\PINNs\Rabi_without_data_train_hpo\rabi_pinn_pura_wandb.py
                python: CPython 3.11.7
                root: C:\Users\CAMILO\Documents\PINNs\Rabi_without_data_train_hpo
                startedAt: "2026-02-17T18:00:19.088729Z"
                writerId: nyukj6wb6520ksdrr8zua6otp025cjq8
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.11.7
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
Delta:
    value: 0
Omega:
    value: 1
T_max:
    value: 20
activation:
    value: silu
dropout:
    value: 0.1
epochs:
    value:
        - 30000
        - 50000
gamma:
    value: 0.1
grad_clip:
    value: 0.5
hidden_layers:
    value: 6
lam_con:
    value: 5
lam_ic:
    value: 200
lam_phys:
    value: 1
log_every:
    value: 50
lr:
    value: 0.004780262512219954
lr_decay:
    value: 0.8
n_collocation:
    value: 3000
neurons:
    value: 128
optimizer:
    value: adamw
scheduler:
    value: cosine
step_size:
    value: 8000
weight_decay:
    value: 0
