_wandb:
    value:
        cli_version: 0.25.0
        e:
            8vrtxp0kfeobnwnoxtpl61uwpiu9r33w:
                args:
                    - --mode
                    - sweep
                    - --count
                    - "20"
                codePath: rabi_pinn_pura_wandb.py
                codePathLocal: rabi_pinn_pura_wandb.py
                email: alberto.estrada@udea.edu.co
                executable: C:\Users\CAMILO\Documents\PINNs\pinn_env\Scripts\python.exe
                host: LAPTOP-9ACAG0LI
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\CAMILO\Documents\PINNs\Rabi_without_data_train_hpo\rabi_pinn_pura_wandb.py
                python: CPython 3.11.7
                root: C:\Users\CAMILO\Documents\PINNs\Rabi_without_data_train_hpo
                startedAt: "2026-02-17T18:00:30.246248Z"
                writerId: 8vrtxp0kfeobnwnoxtpl61uwpiu9r33w
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.11.7
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
Delta:
    value: 0
Omega:
    value: 1
T_max:
    value: 20
activation:
    value: silu
dropout:
    value: 0.1
epochs:
    value:
        - 30000
        - 50000
gamma:
    value: 0.1
grad_clip:
    value: 1
hidden_layers:
    value: 5
lam_con:
    value: 10
lam_ic:
    value: 50
lam_phys:
    value: 5
log_every:
    value: 50
lr:
    value: 0.0001600067913238011
lr_decay:
    value: 0.8
n_collocation:
    value: 2000
neurons:
    value: 128
optimizer:
    value: adamw
scheduler:
    value: multistep
step_size:
    value: 5000
weight_decay:
    value: 1e-05
