_wandb:
    value:
        cli_version: 0.25.0
        e:
            kz5t7t1uvc7n3a7hbkd8b7mcx9osv1d7:
                codePath: rabi_pinn_wandb.py
                codePathLocal: rabi_pinn_wandb.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "511190233088"
                        used: "461143822336"
                email: alberto.estrada@udea.edu.co
                executable: C:\Program Files\Python311\python.exe
                host: LAPTOP-9ACAG0LI
                memory:
                    total: "16456183808"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\CAMILO\Downloads\rabi_pinn_wandb.py
                python: CPython 3.11.7
                root: C:\Users\CAMILO\Downloads
                startedAt: "2026-02-17T05:21:24.164914Z"
                writerId: kz5t7t1uvc7n3a7hbkd8b7mcx9osv1d7
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.7
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
Delta:
    value: 0
Omega:
    value: 1
T_max:
    value: 20
activation:
    value: tanh
batch_size:
    value: 512
dropout:
    value: 0
epochs:
    value: 20000
gamma:
    value: 0.1
grad_clip:
    value: 1
hidden_layers:
    value: 5
lam_con:
    value: 20
lam_data:
    value: 50
lam_ic:
    value: 200
lam_phys:
    value: 1
log_every:
    value: 50
lr:
    value: 0.0005
lr_decay:
    value: 0.5
n_collocation:
    value: 2000
neurons:
    value: 128
optimizer:
    value: adam
scheduler:
    value: multistep
weight_decay:
    value: 0
