_wandb:
    value:
        cli_version: 0.25.0
        e:
            u2yma0anria066cie66ignf6chxoeuqn:
                args:
                    - --mode
                    - sweep
                    - --count
                    - "20"
                codePath: rabi_pinn_pura_wandb.py
                codePathLocal: rabi_pinn_pura_wandb.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "511190233088"
                        used: "459512930304"
                email: alberto.estrada@udea.edu.co
                executable: C:\Users\CAMILO\Documents\PINNs\pinn_env\Scripts\python.exe
                host: LAPTOP-9ACAG0LI
                memory:
                    total: "16456183808"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\CAMILO\Documents\PINNs\Rabi_without_data_train_hpo\rabi_pinn_pura_wandb.py
                python: CPython 3.11.7
                root: C:\Users\CAMILO\Documents\PINNs\Rabi_without_data_train_hpo
                startedAt: "2026-02-17T18:00:45.332767Z"
                writerId: u2yma0anria066cie66ignf6chxoeuqn
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.11.7
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
Delta:
    value: 0
Omega:
    value: 1
T_max:
    value: 20
activation:
    value: tanh
dropout:
    value: 0.05
epochs:
    value:
        - 30000
        - 50000
gamma:
    value: 0.1
grad_clip:
    value: 2
hidden_layers:
    value: 3
lam_con:
    value: 50
lam_ic:
    value: 500
lam_phys:
    value: 0.5
log_every:
    value: 50
lr:
    value: 0.00031105199872376744
lr_decay:
    value: 0.8
n_collocation:
    value: 2000
neurons:
    value: 64
optimizer:
    value: adamw
scheduler:
    value: cosine
step_size:
    value: 5000
weight_decay:
    value: 0.0001
