_wandb:
    value:
        cli_version: 0.25.0
        e:
            dx0lo7jiufnb4vhezc6vudxqpnkqzocp:
                codePath: rabi_pinn_pura_wandb.py
                codePathLocal: rabi_pinn_pura_wandb.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "511190233088"
                        used: "463986565120"
                email: alberto.estrada@udea.edu.co
                executable: C:\Users\CAMILO\Documents\PINNs\pinn_env\Scripts\python.exe
                host: LAPTOP-9ACAG0LI
                memory:
                    total: "16456183808"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\CAMILO\Documents\PINNs\Rabi_without_data_train\rabi_pinn_pura_wandb.py
                python: CPython 3.11.7
                root: C:\Users\CAMILO\Documents\PINNs\Rabi_without_data_train
                startedAt: "2026-02-17T15:30:16.423981Z"
                writerId: dx0lo7jiufnb4vhezc6vudxqpnkqzocp
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.7
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
Delta:
    value: 0
Omega:
    value: 1
T_max:
    value: 20
activation:
    value: tanh
dropout:
    value: 0
epochs:
    value: 20000
gamma:
    value: 0.1
grad_clip:
    value: 1
hidden_layers:
    value: 4
lam_con:
    value: 20
lam_ic:
    value: 200
lam_phys:
    value: 1
log_every:
    value: 50
lr:
    value: 0.0005
lr_decay:
    value: 0.9
n_collocation:
    value: 2000
neurons:
    value: 64
optimizer:
    value: adam
scheduler:
    value: step
step_size:
    value: 5000
weight_decay:
    value: 0
